### ISSUE TITLE
Sintesis-Sandra

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/actividad-3-sintesis-SANDRAVELASCO#2]
[Sintesis-SandraVelasco.pdf](https://github.com/user-attachments/files/16831805/Sintesis-SandraVelasco.pdf)

**Comment by saul19bautista** [comment]
BIEN DESARROLLADO 
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
